theme: jekyll-theme-hacker
title: AmberElec
github.repository_url: https://github.com/AmberElec/AmberElec

sass:
  sass_dir: assets/css

plugins:
  - custom_filter

tipue_search:
  include:
    pages: true