theme: jekyll-theme-hacker
title: PineappleELEC
github.repository_url: https://github.com/351ELEC/351ELEC

sass:
  sass_dir: assets/css

plugins:
  - custom_filter

tipue_search:
  include:
    pages: true